HS-Continuity/Mobile

src/App.jsx, src/apis/data.json, src/apis/index.js, src/components/Product/ProductItem.jsx, src/pages/ProductDetail.jsx, src/pages/Shop.jsx, src/stores/useShopStore.js
[![KAN-121](https://badgen.net/badge/JIRA/KAN-121/blue?icon=jira)](https://jira.company.com/browse/KAN-121) [![PR-7](https://badgen.net/badge/Preview/PR-7/blue)](https://pr-7.company.com) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=HS-Continuity&utm_campaign=badge_info)
- 판매자 소개 페이지 구현
- {KAN-174}
- KAN-174
[KAN-121]: https://hysoung-kosa-team4.atlassian.net/browse/KAN-121?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> KAN-121 feat/ 판매자 업체 소개 페이지

src/App.jsx, src/pages/Order.jsx, src/pages/OrderFail.jsx, src/pages/OrderSuccess.jsx
[![KAN-125](https://badgen.net/badge/JIRA/KAN-125/blue?icon=jira)](https://jira.company.com/browse/KAN-125) [![PR-9](https://badgen.net/badge/Preview/PR-9/blue)](https://pr-9.company.com) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=HS-Continuity&utm_campaign=badge_info)
- 구현 기능을 적어주세요.
- KAN-203
- /order-success : 주문 결제 성공 페이지
- /order-fail : 주문 결제 실패 페이지
- 현재 db 어떻게 날라올지 몰라서 json-server 연동 미구현
[KAN-125]: https://hysoung-kosa-team4.atlassian.net/browse/KAN-125?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> KAN-203 feat:주문확인 페이지 구현

src/apis/data.json, src/apis/index.js, src/pages/Coupon.jsx, src/stores/useCouponStore.js
[![KAN-127](https://badgen.net/badge/JIRA/KAN-127/blue?icon=jira)](https://jira.company.com/browse/KAN-127) [![PR-10](https://badgen.net/badge/Preview/PR-10/blue)](https://pr-10.company.com) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=HS-Continuity&utm_campaign=badge_info)
- 회원별 쿠폰 보유 목록 조회 및 출력
- KAN-205
[KAN-127]: https://hysoung-kosa-team4.atlassian.net/browse/KAN-127?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> KAN-127 feat: 쿠폰함 페이지

src/components/Layouts/OrderLayout.jsx, src/components/Login/LoginLayout.jsx, src/components/Mypage/MypageHeader.jsx, src/components/Mypage/MypageLayout.jsx, src/components/Mypage/MypageMenu.jsx, src/pages/Mypage.jsx, src/pages/Profile.jsx, src/stores/useMemberStore.js
[![KAN-128](https://badgen.net/badge/JIRA/KAN-128/blue?icon=jira)](https://jira.company.com/browse/KAN-128) [![PR-11](https://badgen.net/badge/Preview/PR-11/blue)](https://pr-11.company.com) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=HS-Continuity&utm_campaign=badge_info)
- 회원 개인 정보 조회
- 비밀번호 변경
- KAN-206
- KAN-202 : 주문 페이지 레이아웃
- KAN-166 : 로그인 페이지 레이아웃
- 현재 비밀번호 일치 로직을 백엔드에서 해야하는지 고민
[KAN-128]: https://hysoung-kosa-team4.atlassian.net/browse/KAN-128?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> KAN-128 feat: 개인정보수정 페이지

src/pages/Payment.jsx
[![KAN-129](https://badgen.net/badge/JIRA/KAN-129/blue?icon=jira)](https://jira.company.com/browse/KAN-129) [![PR-12](https://badgen.net/badge/Preview/PR-12/blue)](https://pr-12.company.com) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=HS-Continuity&utm_campaign=badge_info)
- 결제 수단
- KAN-127
- 배송지마다 이름과 전화번호를 입력하여, 더 편리한 기능 제공 예정
[KAN-129]: https://hysoung-kosa-team4.atlassian.net/browse/KAN-129?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> KAN-207 feat:결제수단 관리 기능

src/components/Mypage/AddAddressModaljsx, src/components/Order/AddressModal.jsx, src/components/Order/DeliveryAddress.jsx, src/pages/Address.jsx
[![KAN-130](https://badgen.net/badge/JIRA/KAN-130/blue?icon=jira)](https://jira.company.com/browse/KAN-130) [![PR-13](https://badgen.net/badge/Preview/PR-13/blue)](https://pr-13.company.com) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=HS-Continuity&utm_campaign=badge_info)
- 배송지 관리 기능 구현
- 기본 배송지 설정
- KAN-208
[KAN-130]: https://hysoung-kosa-team4.atlassian.net/browse/KAN-130?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> KAN-130 feat/주소지관리 페이지

src/components/Order/ConsentPayment.jsx, src/pages/OrderHistory.jsx, src/pages/Subscriptions.jsx, src/stores/useOrderStore.js
[![KAN-131](https://badgen.net/badge/JIRA/KAN-131/blue?icon=jira)](https://jira.company.com/browse/KAN-131) [![PR-14](https://badgen.net/badge/Preview/PR-14/blue)](https://pr-14.company.com) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=HS-Continuity&utm_campaign=badge_info)
- KAN-203
[KAN-131]: https://hysoung-kosa-team4.atlassian.net/browse/KAN-131?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Kan 131  feat/리뷰작성 페이지

src/apis/Customer.js, src/pages/Shop.jsx
[![KAN-306](https://badgen.net/badge/JIRA/KAN-306/blue?icon=jira)](https://jira.company.com/browse/KAN-306) [![PR-16](https://badgen.net/badge/Preview/PR-16/blue)](https://pr-16.company.com) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=HS-Continuity&utm_campaign=badge_info)
- 판매자 업체 페이지 API 수정
- KAN-349
[KAN-306]: https://hysoung-kosa-team4.atlassian.net/browse/KAN-306?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> KAN-306 refactor: 판매자 업체 페이지 API 수정

src/App.jsx, src/apis/Cart.js, src/apis/data.json, src/components/Mypage/AddAddressModal.jsx, src/components/Order/OrderItems.jsx, src/components/Order/OrderPrice.jsx, src/hooks/useOrderItemsValidation.js, src/pages/Cart.jsx, src/pages/Order.jsx, src/pages/OrderHistory.jsx, src/pages/SignUp.jsx, src/pages/SubscriptionOrder.jsx, src/pages/SubscriptionSetup.jsx
[![KAN-307](https://badgen.net/badge/JIRA/KAN-307/blue?icon=jira)](https://jira.company.com/browse/KAN-307) [![PR-19](https://badgen.net/badge/Preview/PR-19/blue)](https://pr-19.company.com) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=HS-Continuity&utm_campaign=badge_info)
- 장바구니 API 변경
- KAN-351
- KAN-422 배송지 관련(단순 변수 수정)
- KAN-424 일반 주문 관련(단순 변수 수정)
- KAN-427 정기 주문 관련(단순 변수 수정)
- KAN-343 회원가입 관련(단순 변수 수정)
[KAN-307]: https://hysoung-kosa-team4.atlassian.net/browse/KAN-307?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> KAN-307 refactor: 장바구니 페이지

src/apis/Product.js
[![KAN-308](https://badgen.net/badge/JIRA/KAN-308/blue?icon=jira)](https://jira.company.com/browse/KAN-308) [![PR-20](https://badgen.net/badge/Preview/PR-20/blue)](https://pr-20.company.com) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=HS-Continuity&utm_campaign=badge_info)
- API 충돌 해결
- KAN-353
=> KAN-353 hotfix: API 충돌 해결

src/components/Product/DetailImage.jsx, src/components/Product/PriceBox.jsx, src/components/Product/ProductItem.jsx, src/components/Product/ProductList.jsx, src/components/Product/ProductTopHeader.jsx, src/components/Product/ReviewList.jsx, src/pages/product/Modal.jsx, src/pages/product/ProductInfoModal.jsx, src/pages/product/index.jsx
[![KAN-487](https://badgen.net/badge/JIRA/KAN-487/blue?icon=jira)](https://jira.company.com/browse/KAN-487) [![PR-23](https://badgen.net/badge/Preview/PR-23/blue)](https://pr-23.company.com) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=HS-Continuity&utm_campaign=badge_info)
- 상품 고시 내용 Modal 추가
- KAN-487
[KAN-487]: https://hysoung-kosa-team4.atlassian.net/browse/KAN-487?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> KAN-487 refactor: 식품 상세 페이지

src/pages/search/SearchResult.jsx, src/pages/search/index.jsx
[![KAN-488](https://badgen.net/badge/JIRA/KAN-488/blue?icon=jira)](https://jira.company.com/browse/KAN-488) [![PR-24](https://badgen.net/badge/Preview/PR-24/blue)](https://pr-24.company.com) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=HS-Continuity&utm_campaign=badge_info)
- 간격 및 스타일 수정
- KAN-488
[KAN-488]: https://hysoung-kosa-team4.atlassian.net/browse/KAN-488?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> KAN-488 style: 검색 페이지

src/components/Layouts/OrderLayout.jsx, src/components/Order/ConsentPayment.jsx, src/pages/cart/index.jsx, src/pages/order/index.jsx, src/pages/shop/index.jsx, src/pages/subscriptionOrder/SubscriptionOrder.jsx, src/pages/subscriptionOrder/SubscriptionSetup.jsx
[![KAN-489](https://badgen.net/badge/JIRA/KAN-489/blue?icon=jira)](https://jira.company.com/browse/KAN-489) [![PR-25](https://badgen.net/badge/Preview/PR-25/blue)](https://pr-25.company.com) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=HS-Continuity&utm_campaign=badge_info)
- 장바구니 스타일 변경
- 주문 스타일 변경
- 판매자 사이트 스타일 변경
- Close#{349}
- Close#{355}
- #{489}
[KAN-489]: https://hysoung-kosa-team4.atlassian.net/browse/KAN-489?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> KAN-489 style: 장바구니 페이지

src/components/Order/AddAddressModal.jsx, src/components/Order/AddressEditModal.jsx, src/components/Order/AddressModal.jsx, src/components/Order/AddressRegisterModal.jsx, src/components/Order/CardRegisterModal.jsx, src/components/Order/ConsentPayment.jsx, src/components/Order/DeliveryAddress.jsx, src/components/Order/MemberCouponList.jsx, src/components/Order/OrderItems.jsx, src/components/Order/OrderMemberInfo.jsx, src/components/Order/OrderPrice.jsx, src/components/Order/Payment.jsx, src/components/Order/VirtualKeypad.jsx, src/components/Skeletons/AddressSkeleton.jsx, src/components/Skeletons/CardSkeleton.jsx, src/components/Skeletons/CouponSkeleton.jsx, src/pages/address/NoAddress.jsx, src/pages/address/index.jsx, src/pages/coupon/NoCoupon.jsx, src/pages/coupon/index.jsx, src/pages/order/index.jsx, src/pages/payment/NoCard.jsx, src/pages/payment/index.jsx
=> KAN-571 style: 주문 정보 스타일 변경

src/components/Layouts/CategoryMenu.jsx, src/components/Mypage/MypageLayout.jsx, src/pages/cart/EmptyCart.jsx, src/pages/cart/index.jsx, src/pages/home/ProductSlider.jsx, src/pages/memberInfo/MypageMenu.jsx, src/pages/memberInfo/Profile.jsx, src/pages/memberInfo/index.jsx, src/pages/search/SearchResult.jsx, src/pages/search/index.jsx, src/pages/subscriptionOrder/SubscriptionOrder.jsx, src/pages/subscriptionOrder/SubscriptionSetup.jsx
- 마이페이지 스타일 변경
- KAN-573
- KAN-307(장바구니)
- KAN-304(메인페이지)
- KAN-310(정기주문)
=> KAN-573 style: 마이 페이지 스타일 변경

.github/workflows/mobile-aws.yml
[![KAN-653](https://badgen.net/badge/JIRA/KAN-653/blue?icon=jira)](https://jira.company.com/browse/KAN-653) [![PR-31](https://badgen.net/badge/Preview/PR-31/blue)](https://pr-31.company.com) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=HS-Continuity&utm_campaign=badge_info)
- 모바일서비스 배포자동화 스크립트 작성
- Close#{653}
[KAN-653]: https://hysoung-kosa-team4.atlassian.net/browse/KAN-653?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> KAN-653 모바일서비스 배포자동화 스크립트 작성

src/apis/apiUtils.js, src/components/Layouts/BottomNav.jsx, src/components/Layouts/CategoryData.jsx, src/components/Layouts/CategoryMenu.jsx, src/components/Layouts/RecentSearches.jsx, src/components/Layouts/SearchBar.jsx, src/components/Layouts/TopHeader.jsx, src/components/Mypage/MypageHeader.jsx, src/components/Product/AdvertisementProductItem.jsx, src/components/Product/AdvertisementProductList.jsx, src/components/Skeletons/CardSkeleton.jsx, src/components/Skeletons/CategorySkeleton.jsx, src/components/Skeletons/CouponSkeleton.jsx, src/components/Skeletons/FetchAllSkeleton.jsx, src/components/Skeletons/FetchingNextSkeleton.jsx, src/components/Skeletons/OrderSkeleton.jsx, src/components/Skeletons/ProductSkeleton.jsx, src/components/Skeletons/Skeleton.jsx, src/components/Skeletons/TimesaleListSkeleton.jsx, src/pages/address/NoAddress.jsx, src/pages/home/CategoryGrid.jsx, src/pages/home/index.jsx, src/pages/search/index.jsx, src/pages/shop/index.jsx
[![KAN-662](https://badgen.net/badge/JIRA/KAN-662/blue?icon=jira)](https://jira.company.com/browse/KAN-662) [![PR-33](https://badgen.net/badge/Preview/PR-33/blue)](https://pr-33.company.com) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=HS-Continuity&utm_campaign=badge_info)
- 광고 제품 슬라이더 표시
- Skeleton UI 설정
- Close#{306} 판매자 페이지
- KAN-662
[KAN-662]: https://hysoung-kosa-team4.atlassian.net/browse/KAN-662?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> KAN-662 refactor: 메인 페이지

src/components/Product/CountdownTimer.jsx, src/components/Product/CountdownTimer.module.css, src/pages/eco/index.jsx, src/pages/general/index.jsx, src/pages/product/Modal.jsx, src/pages/product/ProductInfoModal.jsx, src/pages/product/index.jsx, src/pages/review/ReviewApply.jsx, src/pages/timeSale/index.jsx, src/pages/timeSale/timeSaleDetail.jsx, src/pages/timeSale/timeSaleItem.jsx, src/pages/timeSale/timeSaleItem.module.css, src/pages/timeSale/timeSaleList.jsx
[![KAN-664](https://badgen.net/badge/JIRA/KAN-664/blue?icon=jira)](https://jira.company.com/browse/KAN-664) [![PR-34](https://badgen.net/badge/Preview/PR-34/blue)](https://pr-34.company.com) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=HS-Continuity&utm_campaign=badge_info)
- 타임세일 페이지 구현
- Close#{313} 리뷰
- KAN-664
[KAN-664]: https://hysoung-kosa-team4.atlassian.net/browse/KAN-664?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> KAN-664 feat: 타임 세일 페이지

src/components/Order/GetStatusStyle.jsx, src/components/Order/GetStatusText.jsx, src/pages/orderManage/OrderDetail.jsx, src/pages/orderManage/OrderList.jsx, src/pages/orderManage/RefundApply.jsx, src/pages/orderManage/index.jsx
[![KAN-666](https://badgen.net/badge/JIRA/KAN-666/blue?icon=jira)](https://jira.company.com/browse/KAN-666) [![PR-37](https://badgen.net/badge/Preview/PR-37/blue)](https://pr-37.company.com) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=HS-Continuity&utm_campaign=badge_info)
- 일반 주문 내역 페이지 구현
- KAN-666
[KAN-666]: https://hysoung-kosa-team4.atlassian.net/browse/KAN-666?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> KAN-666 feat: 일반 주문 관리 페이지

src/components/Order/SubscriptionInfo.jsx, src/pages/subscriptionOrder/SubscriptionOrder.jsx, src/pages/subscriptionOrderManage/SubscriptionOrderDetail.jsx, src/pages/subscriptionOrderManage/SubscriptionOrderList.jsx, src/pages/subscriptionOrderManage/index.jsx
[![KAN-667](https://badgen.net/badge/JIRA/KAN-667/blue?icon=jira)](https://jira.company.com/browse/KAN-667) [![PR-38](https://badgen.net/badge/Preview/PR-38/blue)](https://pr-38.company.com) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=HS-Continuity&utm_campaign=badge_info)
- 정기 주문 관리 페이지
- KAN-665 정기 주문
- KAN-667
- 다음 정기 배송 일자를 지났다면 정기 주문 연기, 취소 불가능한 상태
[KAN-667]: https://hysoung-kosa-team4.atlassian.net/browse/KAN-667?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> KAN-667 feat: 정기 주문 관리 페이지

src/apis/index.js
[![KAN-673](https://badgen.net/badge/JIRA/KAN-673/blue?icon=jira)](https://jira.company.com/browse/KAN-673) [![PR-39](https://badgen.net/badge/Preview/PR-39/blue)](https://pr-39.company.com) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=HS-Continuity&utm_campaign=badge_info)
- 트래픽 몰리는 시간 고려 기능
- 리뷰 등록 API
- Close#{issue 번호}
- 만약 해당 이슈 close 안할거면 #{issue 번호}
- 예외 처리를 해야하는데 아직 못했습니다.
[KAN-673]: https://hysoung-kosa-team4.atlassian.net/browse/KAN-673?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> KAN-673 refactor: API 수정

src/apis/index.js, src/components/Product/ProductItem.jsx, src/pages/address/index.jsx, src/pages/login/index.jsx, src/pages/payment/index.jsx, src/pages/review/ReviewApply.jsx, src/pages/signup/index.jsx
[![KAN-694](https://badgen.net/badge/JIRA/KAN-694/blue?icon=jira)](https://jira.company.com/browse/KAN-694) [![PR-41](https://badgen.net/badge/Preview/PR-41/blue)](https://pr-41.company.com) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=HS-Continuity&utm_campaign=badge_info)
- 회원가입 중복 검사
- KAN-694
[KAN-694]: https://hysoung-kosa-team4.atlassian.net/browse/KAN-694?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> KAN-694 feat: 회원가입 중복 검사

.github/workflows/mobile-aws.yml, src/apis/apiUtils.js, src/stores/useAuthStore.js
[![KAN-720](https://badgen.net/badge/JIRA/KAN-720/blue?icon=jira)](https://jira.company.com/browse/KAN-720) [![PR-44](https://badgen.net/badge/Preview/PR-44/blue)](https://pr-44.company.com) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=HS-Continuity&utm_campaign=badge_info)
- 모바일 배포자동화 스크립트 수정
- Close#{720}
[KAN-720]: https://hysoung-kosa-team4.atlassian.net/browse/KAN-720?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> KAN-720 feat: 모바일 배포자동화 스크립트 수정

src/apis/apiUtils.js, src/apis/axiosConfig.js, src/apis/index.js
[![KAN-721](https://badgen.net/badge/JIRA/KAN-721/blue?icon=jira)](https://jira.company.com/browse/KAN-721) [![PR-46](https://badgen.net/badge/Preview/PR-46/blue)](https://pr-46.company.com) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=HS-Continuity&utm_campaign=badge_info)
- 모바일 BaseUrl 수정
- Close#{721}
[KAN-721]: https://hysoung-kosa-team4.atlassian.net/browse/KAN-721?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> KAN-721 refactor: 모바일 BaseUrl 수정

src/stores/useAuthStore.js
[![KAN-724](https://badgen.net/badge/JIRA/KAN-724/blue?icon=jira)](https://jira.company.com/browse/KAN-724) [![PR-48](https://badgen.net/badge/Preview/PR-48/blue)](https://pr-48.company.com) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=HS-Continuity&utm_campaign=badge_info)
- 모바일 refresh token 버그 수정
- Close#{724}
[KAN-724]: https://hysoung-kosa-team4.atlassian.net/browse/KAN-724?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> KAN-724 refactor: 모바일 refresh token 버그 수정

src/stores/useAuthStore.js
- 모바일 refresh token 버그 수정2
- Close#{725}
=> KAN-725 refactor: 모바일 refresh token 버그 수정2

src/stores/useAuthStore.js
[![KAN-726](https://badgen.net/badge/JIRA/KAN-726/blue?icon=jira)](https://jira.company.com/browse/KAN-726) [![PR-51](https://badgen.net/badge/Preview/PR-51/blue)](https://pr-51.company.com) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=HS-Continuity&utm_campaign=badge_info)
- 모바일서비스 브랜치충돌 예방
- Close#{726}
[KAN-726]: https://hysoung-kosa-team4.atlassian.net/browse/KAN-726?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> KAN-726 feat: 모바일서비스 브랜치충돌 예방

src/stores/useAuthStore.js
[![PR-52](https://badgen.net/badge/Preview/PR-52/blue)](https://pr-52.company.com) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=HS-Continuity&utm_campaign=badge_info)
모바일 연이음 페이지 (v1.3)
- 브랜치 충돌 예방
=> 모바일 연이음 페이지 (v1.3)

src/components/Layouts/PopularKeywords.jsx
[![KAN-733](https://badgen.net/badge/JIRA/KAN-733/blue?icon=jira)](https://jira.company.com/browse/KAN-733) [![PR-54](https://badgen.net/badge/Preview/PR-54/blue)](https://pr-54.company.com) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=HS-Continuity&utm_campaign=badge_info)
- 모바일서비스 검색어랭킹 버그수정
- Close#{733}
[KAN-733]: https://hysoung-kosa-team4.atlassian.net/browse/KAN-733?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> KAN-733 fix: 모바일서비스 검색어랭킹 버그수정

src/apis/index.js, src/components/Login/ProtectedRoute.jsx, src/components/Order/GetStatusText.jsx, src/components/Order/Payment.jsx, src/pages/cart/index.jsx, src/pages/home/ProductSlider.jsx, src/pages/memberInfo/MypageMenu.jsx, src/pages/order/index.jsx, src/pages/shop/index.jsx, src/pages/subscriptionOrder/SubscriptionOrder.jsx, src/pages/subscriptionOrder/SubscriptionSetup.jsx
[![KAN-745](https://badgen.net/badge/JIRA/KAN-745/blue?icon=jira)](https://jira.company.com/browse/KAN-745) [![PR-58](https://badgen.net/badge/Preview/PR-58/blue)](https://pr-58.company.com) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=HS-Continuity&utm_campaign=badge_info)
- 장바구니 삭제 기능
- KAN-745
[KAN-745]: https://hysoung-kosa-team4.atlassian.net/browse/KAN-745?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> KAN-745 fix: 내용 디자인 수정

src/pages/orderManage/OrderList.jsx, src/pages/subscriptionOrderManage/SubscriptionOrderList.jsx
[![PR-63](https://badgen.net/badge/Preview/PR-63/blue)](https://pr-63.company.com) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=HS-Continuity&utm_campaign=badge_info)
=> 모바일 연이음 페이지 (v1.6)

src/pages/subscriptionOrderManage/SubscriptionOrderList.jsx
[![KAN-742](https://badgen.net/badge/JIRA/KAN-742/blue?icon=jira)](https://jira.company.com/browse/KAN-742) [![PR-64](https://badgen.net/badge/Preview/PR-64/blue)](https://pr-64.company.com) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=HS-Continuity&utm_campaign=badge_info)
- 정기주문페이지 상품서비스이용불가 수정
- Close#{742}
=> KAN-742 fix: 정기주문페이지

src/pages/product/DetailCategory.jsx, src/pages/subscriptionOrder/SubscriptionOrder.jsx
[![KAN-752](https://badgen.net/badge/JIRA/KAN-752/blue?icon=jira)](https://jira.company.com/browse/KAN-752) [![PR-65](https://badgen.net/badge/Preview/PR-65/blue)](https://pr-65.company.com) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=HS-Continuity&utm_campaign=badge_info)
- 스크롤 버그 해결
- KAN-752
- 진짜 마지막 PR인 것 같아서 떨리기도 하고,, 설렌다!
=> KAN-752 fix정기주문 스크롤버그 해결

src/pages/orderManage/OrderList.jsx, src/pages/subscriptionOrderManage/SubscriptionOrderList.jsx
[![PR-66](https://badgen.net/badge/Preview/PR-66/blue)](https://pr-66.company.com) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=HS-Continuity&utm_campaign=badge_info)
**1.7** 버전으로 마무리 하겠습니다.
다들 고생 많았습니다!!
=> 모바일 연이음 페이지 (v1.7)

src/pages/subscriptionOrderManage/SubscriptionOrderDetail.jsx
[![PR-67](https://badgen.net/badge/Preview/PR-67/blue)](https://pr-67.company.com) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=HS-Continuity&utm_campaign=badge_info)
- 모바일 연이음 페이지 (v1.8) 배포
- Close#{issue 번호}
- 만약 해당 이슈 close 안할거면 #{issue 번호}
- 리뷰어에게 참고할만한 사항을 입력해주세요.
=> 모바일 연이음 페이지 (v1.8)

src/pages/subscriptionOrderManage/SubscriptionOrderDetail.jsx
[![PR-68](https://badgen.net/badge/Preview/PR-68/blue)](https://pr-68.company.com) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=HS-Continuity&utm_campaign=badge_info)
- 모바일 연이음 페이지 (v1.8) 
- Close#{issue 번호}
- 만약 해당 이슈 close 안할거면 #{issue 번호}
- 리뷰어에게 참고할만한 사항을 입력해주세요.
=> 모바일 연이음 페이지 (v1.9)
